<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="./views/css/custom.css">
</head>
<body>
    <div class="container">
		<header class="row justify-content-between align-items-center">
			<h1 class="col-auto">Chat Room</h1>
			<nav class="col-auto">	
				<ul class="nav">
                    <li><a href="index.php">Inicio</a></li>
                    <?php
					if ($_SESSION['user'] -> getName()=="") {
						echo '<li><a href="index.php?login">Login</a></li>';
                    } else {
						echo '<li><a href="index.php?login&logout">Salir</a></li>';
					}
					?>
                </ul>
            </nav>
        </header>
        <section>
            <div class="row justify-content-center">
                <div class="col-12 col-md-5">
                    <h2 class="text-center pt-5 mb-5">Creacion de una sala</h2>

                    <form action="index.php?addSala" method="POST">
                        <div class="mb-4">
                            <label class="form-label">Nombre de sala</label>
                            <input type="text" class="form-control" name="name">
                        </div>
                        <div class="mb-4">
                            <label class="form-label">Descripcion de la sala</label>
                            <textarea name="descripcion" class="form-control"></textarea>
                        </div>
                        <div class="d-grid">
                            <input type="submit" class="btn btn-primary" name="addSala" value="Crear sala">
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
    </body>
</html>