<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Añadir</title>
        <link rel="stylesheet" href="views/css/style.css">
    </head>
    <body>
    <header>
		<h1>Blog</h1>
		<nav>	
		<div id="menuBuscar">
			<form action="index.php?buscador" method="post">
				<input type="text" name="buscar" placeholder="buscar...">
				<input type="submit" name="busqueda" value="buscar"/>
			</form>
		</div>
			<ul>
				<li><a href="index.php">Inicio</a></li>
				<?php
				if($_SESSION['user'] -> getName()=="")
					echo '<li><a href="index.php?login">Login</a></li>';
				else if ($_SESSION['user'] -> getId_rol() == 1) {
					echo '<li><a href="index.php?login&logout">Salir</a></li>';
				} else {
					// echo 'Hola '.$_SESSION['user']->getName();
					echo '<li><a href="index.php?login&logout">Salir</a></li>'.'
					<li><a href="index.php?añadir">Articulos</a></li>
					<li><a href="index.php?admin">Administracion</a></li>';
				}
				?>
			</ul>
		</nav>
	</header>
    <section>
        <h2>Añadir un articulo</h2>
        <div id="addArticulo">
            <form action="index.php?añadir" method="post" enctype="multipart/form-data">
                <div id="AddArticuloTitle">
                    <label>Titulo: </label><br>
                    <input type="text" name="title" placeholder="Titulo"/><br>
                    <label>Imagen: </label><br>
                    <input type="file" name="imagen"/><br>
                </div>
                <label>Contenido: </label><br>
                <textarea name="contenido"></textarea><br>
                <input type="submit" name="añadir" value="Subir articulo"/>
            </form>
        </div>
    </section>
</body>
</html>