<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="./views/css/custom.css">
</head>
<body>
    <div class="container">
		<header class="row justify-content-between align-items-center">
			<h1 class="col-auto">Control de trabajadores</h1>
			<nav class="col-auto">	
				<ul class="nav">
                    <li><a href="index.php">Inicio</a></li>
                </ul>
            </nav>
        </header>
            <div>
                <div class="row justify-content-center">
                <section>
                <h1>Administracion</h1>
                <ul>
                    <?php
                    echo '<div id="adminPanel">';
                        // lISTA DE USUARIOS SIN PERMISOS DE ADMINISTRACION
                    echo '<div id="usuariosNormales"><h2>Lista de usuarios</h2>';
                        foreach ($usuarios as $User) {
                            echo '<li>'.$User->getName();
                                echo '<form action="index.php?admin&id_user='.$User->getId().'" method="post">
                                    <input type="submit" name="addAdmin" value="Añadir admin"/>
                                </form></li>';
                        }
                    echo '</div>';
                        // lISTA DE USUARIOS ADMINISTRADORES
                    echo '<div id="usuariosAdmin"><h2>Lista de administradores</h2>';
                        foreach ($usuariosAdmin as $User) {
                            echo '<li>'.$User->getName();
                            echo '<form action="index.php?admin&id_user='.$User->getId().'" method="post">
                                <input type="submit" name="quitarAdmin" value="Quitar admin"/>
                            </form></li>';
                        }
                    echo '</div></div>';
                    ?>
                    
                    
                </ul>
            </div>
            </div>
        </div>
    </div>
    </body>
</html>