<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <h1 align="center">REGISTRAR PELICULAS</h1>

        <form action="index.php?añadir" method="post">
            <input type="text" name="añadir" placeholder="Titulo para añadir">
            <input type="submit" value="Añadir">
        </form>
    </body>
</html>